import {
  CvResume,
  CVTemplate,
  CoverLetter,
  JobApplication,
  NotificationItem,
  InterviewQuestion,
  CareerGoal,
  UserProfile,
} from '../types';

export const initialUser: UserProfile = {
  name: 'Алексей Петров',
  email: 'alex.petrov@cvgen.ai',
  phone: '+375 (29) 303-04-53',
  location: 'Минск, Беларусь',
  headline: 'Senior Fullstack Developer · React & Node.js',
  targetRole: 'Fullstack Developer',
  experienceYears: 9,
  plan: 'pro',
  isAuthenticated: true,
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  cvsCreated: 14,
  linkedinConnected: true,
  githubConnected: true,
};

export const initialTemplates: CVTemplate[] = [
  {
    id: 'tpl-modern',
    name: 'Modern',
    category: 'modern',
    description: 'Двухколоночный шаблон с акцентной панелью. Лучший для IT и digital-специальностей.',
    accentColor: '#10B981',
    previewGradient: 'from-emerald-600 via-teal-500 to-cyan-500',
    isPremium: false,
    suitability: ['IT', 'Digital', 'Marketing'],
    popular: true,
  },
  {
    id: 'tpl-classic',
    name: 'Classic',
    category: 'classic',
    description: 'Классический одноколоночный формат, который пройдёт любую ATS-систему.',
    accentColor: '#3B82F6',
    previewGradient: 'from-blue-600 via-indigo-500 to-violet-500',
    isPremium: false,
    suitability: ['Юристы', 'Финансы', 'HR', 'Госсектор'],
  },
  {
    id: 'tpl-creative',
    name: 'Creative',
    category: 'creative',
    description: 'Яркий дизайн с нестандартной типографикой для дизайнеров и креативных профессий.',
    accentColor: '#F59E0B',
    previewGradient: 'from-amber-500 via-orange-500 to-rose-500',
    isPremium: true,
    suitability: ['Дизайн', 'Креатив', 'Медиа'],
  },
  {
    id: 'tpl-technical',
    name: 'Technical',
    category: 'technical',
    description: 'Оптимизирован под рекрутёров и ATS: чёткие секции, ключевые слова, метрики.',
    accentColor: '#8B5CF6',
    previewGradient: 'from-violet-600 via-purple-500 to-fuchsia-500',
    isPremium: false,
    suitability: ['Инженерия', 'Наука', 'Production'],
    popular: true,
  },
  {
    id: 'tpl-minimal',
    name: 'Minimal',
    category: 'modern',
    description: 'Максимум воздуха и минимализма. Идеален для руководителей и консультантов.',
    accentColor: '#94A3B8',
    previewGradient: 'from-slate-500 via-slate-400 to-zinc-300',
    isPremium: true,
    suitability: ['Топ-менеджмент', 'Консалтинг'],
  },
  {
    id: 'tpl-executive',
    name: 'Executive',
    category: 'classic',
    description: 'Премиальный формат для топ-позиций: резюме-презентация в одну-две страницы.',
    accentColor: '#F43F5E',
    previewGradient: 'from-rose-600 via-red-500 to-orange-500',
    isPremium: true,
    suitability: ['C-Level', 'Директора'],
  },
];

export const initialResumes: CvResume[] = [
  {
    id: 'cv-1',
    name: 'Fullstack Developer 2026',
    title: 'Senior Fullstack Developer',
    templateId: 'tpl-modern',
    status: 'optimized',
    atsScore: 92,
    compatibility: 94,
    completeness: 100,
    createdAt: '2026-01-12',
    updatedAt: '2026-08-05',
    stats: {
      views: 1284,
      downloads: 341,
      applications: 23,
      interviews: 9,
      lastViewed: '2 часа назад',
    },
    personalInfo: {
      fullName: 'Алексей Петров',
      headline: 'Senior Fullstack Developer · React & Node.js',
      email: 'alex.petrov@cvgen.ai',
      phone: '+375 (29) 303-04-53',
      location: 'Минск, Беларусь',
      summary:
        'Fullstack-разработчик с 9-летним опытом. Строю высоконагруженные веб-продукты на React, TypeScript и Node.js. Руководил командами до 8 человек, внедрял CI/CD и сокращал время релиза на 60%. Ищу роль Senior Fullstack / Tech Lead в продуктовой компании.',
      website: 'https://alexpetrov.dev',
      linkedin: 'linkedin.com/in/alexpetrov',
      telegram: '@alexpetrov',
      github: 'github.com/alexpetrov',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
    workExperience: [
      {
        id: 'exp-1',
        company: 'ITransition',
        position: 'Senior Fullstack Developer',
        location: 'Минск, Беларусь',
        startDate: '2022-03',
        endDate: 'Настоящее время',
        current: true,
        description: 'Разработка B2B-платформы аналитики продаж для клиентов из США и ЕС.',
        achievements: [
          'Сократил время загрузки ключевых дашбордов с 4.2с до 1.1с (−74%)',
          'Внедрил микросервисную архитектуру: 12 сервисов на Node.js + PostgreSQL',
          'Менторил 5 джуниоров; трое выросли до мидл-уровня за год',
        ],
        techStack: ['React', 'TypeScript', 'Node.js', 'GraphQL', 'PostgreSQL', 'Kubernetes'],
      },
      {
        id: 'exp-2',
        company: 'EPAM Systems',
        position: 'Frontend Developer',
        location: 'Минск, Беларусь',
        startDate: '2019-06',
        endDate: '2022-02',
        current: false,
        description: 'Крупный финтех-проект для европейского банка: интернет-банкинг и платёжные виджеты.',
        achievements: [
          'Построил дизайн-систему из 40+ переиспользуемых компонентов',
          'Довёл unit-покрытие фронтенда с 12% до 85%',
          'Участвовал в 20+ code-review и ревью архитектуры 5 фич',
        ],
        techStack: ['React', 'Redux', 'Jest', 'Webpack', 'SCSS'],
      },
      {
        id: 'exp-3',
        company: 'SoftClub',
        position: 'Junior Developer',
        location: 'Минск, Беларусь',
        startDate: '2017-07',
        endDate: '2019-05',
        current: false,
        description: 'Разработка внутренних CRM-систем и лендингов для e-commerce клиентов.',
        achievements: ['С 0 построил 8 корпоративных сайтов с CMS', 'Автоматизировал деплой через Jenkins'],
        techStack: ['JavaScript', 'PHP', 'MySQL', 'jQuery', 'Bootstrap'],
      },
    ],
    education: [
      {
        id: 'edu-1',
        institution: 'БГУИР (Белорусский государственный университет информатики и радиоэлектроники)',
        degree: 'Бакалавр',
        field: 'Программная инженерия',
        startDate: '2013-09',
        endDate: '2017-06',
        gpa: '4.8 / 5.0',
        description: 'Дипломная работа: «Проектирование масштабируемых веб-приложений» (оценка 10/10).',
      },
    ],
    skills: [
      { id: 'sk-1', name: 'TypeScript', level: 'expert', category: 'Frontend', years: 6 },
      { id: 'sk-2', name: 'React / Next.js', level: 'expert', category: 'Frontend', years: 7 },
      { id: 'sk-3', name: 'CSS / Tailwind', level: 'advanced', category: 'Frontend', years: 8 },
      { id: 'sk-4', name: 'Node.js', level: 'advanced', category: 'Backend', years: 5 },
      { id: 'sk-5', name: 'GraphQL', level: 'advanced', category: 'Backend', years: 3 },
      { id: 'sk-6', name: 'PostgreSQL', level: 'advanced', category: 'Backend', years: 4 },
      { id: 'sk-7', name: 'Docker / Kubernetes', level: 'intermediate', category: 'Tooling', years: 3 },
      { id: 'sk-8', name: 'CI/CD (GitHub Actions)', level: 'advanced', category: 'Tooling', years: 4 },
      { id: 'sk-9', name: 'Английский (письменный/устный)', level: 'advanced', category: 'Soft', years: 9 },
      { id: 'sk-10', name: 'Менторство и онбординг', level: 'advanced', category: 'Soft', years: 4 },
      { id: 'sk-11', name: 'Unit-тестирование (Jest)', level: 'advanced', category: 'Tooling', years: 5 },
      { id: 'sk-12', name: 'System Design', level: 'intermediate', category: 'Backend', years: 2 },
    ],
    languages: [
      { id: 'lg-1', name: 'Русский', level: 'Родной', levelPercent: 100, certification: 'Native' },
      { id: 'lg-2', name: 'Английский', level: 'C1 — Advanced', levelPercent: 85, certification: 'IELTS 7.5' },
      { id: 'lg-3', name: 'Польский', level: 'B1 — Intermediate', levelPercent: 55 },
    ],
    certificates: [
      { id: 'cert-1', name: 'AWS Certified Developer — Associate', issuer: 'Amazon Web Services', date: '2025-11', credentialUrl: 'aws.cert/alex', verified: true },
      { id: 'cert-2', name: 'GraphQL & Apollo Advanced', issuer: 'Apollo GraphQL', date: '2024-06', credentialUrl: 'apollo.dev', verified: true },
      { id: 'cert-3', name: 'IELTS Academic 7.5', issuer: 'British Council', date: '2024-03', credentialUrl: 'ielts.org', verified: true },
      { id: 'cert-4', name: 'Kubernetes Fundamentals (K8s)', issuer: 'Coursera / Google Cloud', date: '2023-09', credentialUrl: 'coursera.org', verified: false },
    ],
    projects: [
      {
        id: 'pr-1',
        name: 'CVGen',
        role: 'Продукт + Архитектура',
        description: 'AI-платформа генерации резюме: шаблоны, ATS-анализ, сопроводительные письма.',
        techStack: ['React', 'TypeScript', 'Tailwind', 'OpenAI API'],
        url: 'https://cvgen.ai',
        gradient: 'from-emerald-600 to-teal-400',
        highlights: ['500+ пользователей за первый месяц', 'ATS-score 90+ у 78% резюме'],
      },
      {
        id: 'pr-2',
        name: 'FinDash',
        role: 'Lead Frontend Developer',
        description: 'Аналитический дашборд для финтех-стартапа: графики, отчёты, экспорт.',
        techStack: ['React', 'TypeScript', 'Recharts', 'WebSockets'],
        url: 'https://findash.io',
        gradient: 'from-violet-600 to-fuchsia-500',
        highlights: ['Обработка 50k событий в секунду', 'UI-кит из 60+ компонентов'],
      },
      {
        id: 'pr-3',
        name: 'EcoTrack',
        role: 'Fullstack Developer',
        description: 'Мобильное PWA для учёта отходов и эко-инициатив городского сообщества.',
        techStack: ['Next.js', 'Node.js', 'PostgreSQL', 'PWA'],
        url: 'https://ecotrack.app',
        gradient: 'from-cyan-500 to-emerald-400',
        highlights: ['2 000+ активных пользователей', 'Интеграция с картами и QR-кодами'],
      },
    ],
    references: [
      { id: 'ref-1', name: 'Иван Смирнов', position: 'Tech Lead', company: 'ITransition', email: 'i.smirnov@itransition.com', phone: '+375 29 111-22-33', relation: 'Руководитель проекта', rating: 5 },
      { id: 'ref-2', name: 'Мария Ковалёва', position: 'HR Director', company: 'ITransition', email: 'm.kovaleva@itransition.com', phone: '+375 29 444-55-66', relation: 'HR-партнёр', rating: 5 },
    ],
    achievements: [
      { id: 'ac-1', title: '1-е место, хакатон ЦФТ «Финтех 2024»', date: '2024-11', category: 'professional', description: 'Победил с командой в кейсе по open banking API.' },
      { id: 'ac-2', title: '500+ проведённых технических интервью', date: '2023-2026', category: 'professional', description: 'Найм и скрининг кандидатов уровня middle/senior.' },
      { id: 'ac-3', title: 'Open Source: 2 000+ звёзд на GitHub', date: '2025-05', category: 'professional', description: 'Автор библиотеки react-form-kit (популярный Form API).' },
      { id: 'ac-4', title: 'Волонтёр: ментор IT-академии для школьников', date: '2024-2026', category: 'volunteer', description: '30+ учеников, 3 призёра олимпиад.' },
    ],
  },
  {
    id: 'cv-2',
    name: 'Frontend Developer (активный поиск)',
    title: 'Frontend Developer',
    templateId: 'tpl-technical',
    status: 'in_progress',
    atsScore: 74,
    compatibility: 81,
    completeness: 68,
    createdAt: '2026-07-18',
    updatedAt: '2026-08-02',
    stats: {
      views: 312,
      downloads: 58,
      applications: 6,
      interviews: 2,
      lastViewed: '1 день назад',
    },
    personalInfo: {
      fullName: 'Алексей Петров',
      headline: 'Frontend Developer · React',
      email: 'alex.petrov@cvgen.ai',
      phone: '+375 (29) 303-04-53',
      location: 'Минск, Беларусь',
      summary:
        'Frontend-разработчик с 6-летним опытом в React-экосистеме. Умею строить от UI-китов до SSR-приложений.',
      website: 'https://alexpetrov.dev',
      linkedin: 'linkedin.com/in/alexpetrov',
      telegram: '@alexpetrov',
      github: 'github.com/alexpetrov',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
    workExperience: [
      {
        id: 'exp-1',
        company: 'ITransition',
        position: 'Senior Fullstack Developer',
        location: 'Минск, Беларусь',
        startDate: '2022-03',
        endDate: 'Настоящее время',
        current: true,
        description: 'Разработка B2B-платформы аналитики продаж.',
        achievements: ['Сократил загрузку дашбордов на 74%', 'Менторство 5 джуниоров'],
        techStack: ['React', 'TypeScript', 'Node.js'],
      },
    ],
    education: [
      {
        id: 'edu-1',
        institution: 'БГУИР',
        degree: 'Бакалавр',
        field: 'Программная инженерия',
        startDate: '2013-09',
        endDate: '2017-06',
        gpa: '4.8 / 5.0',
        description: '',
      },
    ],
    skills: [
      { id: 'sk-1', name: 'React', level: 'expert', category: 'Frontend', years: 7 },
      { id: 'sk-2', name: 'TypeScript', level: 'advanced', category: 'Frontend', years: 5 },
      { id: 'sk-3', name: 'Tailwind', level: 'advanced', category: 'Frontend', years: 4 },
    ],
    languages: [
      { id: 'lg-1', name: 'Русский', level: 'Родной', levelPercent: 100 },
      { id: 'lg-2', name: 'Английский', level: 'C1', levelPercent: 85 },
    ],
    certificates: [],
    projects: [],
    references: [],
    achievements: [],
  },
  {
    id: 'cv-3',
    name: 'Product Manager',
    title: 'Product Manager / Head of Product',
    templateId: 'tpl-classic',
    status: 'draft',
    atsScore: 58,
    compatibility: 66,
    completeness: 41,
    createdAt: '2026-08-01',
    updatedAt: '2026-08-01',
    stats: {
      views: 0,
      downloads: 0,
      applications: 0,
      interviews: 0,
      lastViewed: '—',
    },
    personalInfo: {
      fullName: 'Алексей Петров',
      headline: 'Product Manager',
      email: 'alex.petrov@cvgen.ai',
      phone: '+375 (29) 303-04-53',
      location: 'Минск, Беларусь',
      summary: '',
      website: '',
      linkedin: 'linkedin.com/in/alexpetrov',
      telegram: '',
      github: '',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
    workExperience: [],
    education: [],
    skills: [],
    languages: [],
    certificates: [],
    projects: [],
    references: [],
    achievements: [],
  },
];

export const initialCoverLetters: CoverLetter[] = [
  {
    id: 'cl-1',
    resumeId: 'cv-1',
    resumeName: 'Fullstack Developer 2026',
    company: 'ITransition',
    position: 'Senior Fullstack Developer',
    tone: 'professional',
    aiGenerated: true,
    status: 'ready',
    createdAt: '2026-08-03',
    content:
      'Здравствуйте! Меня зовут Алексей Петров, и я хочу присоединиться к команде ITransition на позицию Senior Fullstack Developer. За 9 лет я построил 20+ продуктов и сокращал время релиза на 60% в среднем. Уверен, что мой опыт в высоконагруженных дашбордах будет полезен вашей B2B-платформе. Буду рад обсудить детали на созвоне.',
  },
  {
    id: 'cl-2',
    resumeId: 'cv-2',
    resumeName: 'Frontend Developer (активный поиск)',
    company: 'EPAM Systems',
    position: 'Frontend Developer',
    tone: 'formal',
    aiGenerated: true,
    status: 'draft',
    createdAt: '2026-08-04',
    content: 'Шаблон сопроводительного письма. Добавьте персональный абзац о компании.',
  },
  {
    id: 'cl-3',
    resumeId: 'cv-1',
    resumeName: 'Fullstack Developer 2026',
    company: 'Яндекс',
    position: 'Tech Lead, Fullstack',
    tone: 'friendly',
    aiGenerated: false,
    status: 'sent',
    createdAt: '2026-07-28',
    content: 'Привет, команда Яндекс! Мне близка ваша культура инженерной открытости...',
  },
];

export const initialApplications: JobApplication[] = [
  {
    id: 'app-1',
    company: 'Яндекс',
    position: 'Tech Lead, Fullstack',
    salary: 'от 8 000$',
    status: 'interview',
    source: 'Хабр Карьера',
    date: '2026-07-29',
    resumeName: 'Fullstack Developer 2026',
    notes: '2 этап собеседования — системный дизайн, 12 августа.',
    matchScore: 96,
  },
  {
    id: 'app-2',
    company: 'EPAM Systems',
    position: 'Senior Frontend Developer',
    salary: 'от 6 500$',
    status: 'applied',
    source: 'LinkedIn',
    date: '2026-08-02',
    resumeName: 'Frontend Developer (активный поиск)',
    notes: 'Рекрутер ответил, назначили скрининг.',
    matchScore: 88,
  },
  {
    id: 'app-3',
    company: 'iTechArt',
    position: 'Fullstack Engineer',
    salary: 'от 7 000$',
    status: 'saved',
    source: 'Djinni',
    date: '2026-08-05',
    resumeName: 'Fullstack Developer 2026',
    notes: 'Вакансия открыта 2 дня, применить на следующей неделе.',
    matchScore: 83,
  },
  {
    id: 'app-4',
    company: 'Floom',
    position: 'Principal Engineer',
    salary: 'от 9 500$',
    status: 'offer',
    source: 'Рекомендация',
    date: '2026-07-20',
    resumeName: 'Fullstack Developer 2026',
    notes: 'Оффер получен 6 августа. Дедлайн ответа — 20 августа.',
    matchScore: 91,
  },
  {
    id: 'app-5',
    company: 'Wargaming',
    position: 'Frontend Developer',
    salary: 'от 5 500$',
    status: 'rejected',
    source: 'HeadHunter',
    date: '2026-06-15',
    resumeName: 'Frontend Developer (активный поиск)',
    notes: 'Рекрутер сказал: закрыли роль внутри команды.',
    matchScore: 76,
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: '📈 Резюме набрало 1 284 просмотра',
    message: '«Fullstack Developer 2026» обогнало 87% резюме вашей ниши за последнюю неделю.',
    type: 'success',
    timestamp: '10 мин назад',
    isRead: false,
    link: '/analytics',
  },
  {
    id: 'notif-2',
    title: '🤖 AI-рекомендация',
    message: 'Добавьте 3 ключевых навыка из вакансий, на которые вы откликаетесь, — ATS-совместимость вырастет на 6%.',
    type: 'info',
    timestamp: '1 час назад',
    isRead: false,
    link: '/skills',
  },
  {
    id: 'notif-3',
    title: '⚡ Напоминание о собеседовании',
    message: 'Завтра в 14:00 — системный дизайн в Яндекс. Подготовьте архитектуру поискового сервиса.',
    type: 'warning',
    timestamp: '3 часа назад',
    isRead: false,
    link: '/interview',
  },
  {
    id: 'notif-4',
    title: '✨ Новые шаблоны',
    message: 'Добавлены премиум-шаблоны «Creative» и «Executive». Пока доступны для Pro-плана.',
    type: 'info',
    timestamp: 'Вчера',
    isRead: true,
    link: '/templates',
  },
  {
    id: 'notif-5',
    title: '🎯 Срок действия ссылки на резюме',
    message: 'Публичная ссылка резюме «Product Manager» истекает через 7 дней. Продлите, чтобы не терять просмотры.',
    type: 'danger',
    timestamp: '2 дня назад',
    isRead: true,
    link: '/export',
  },
];

export const initialInterviewQuestions: InterviewQuestion[] = [
  {
    id: 'iq-1',
    category: 'System Design',
    question: 'Спроектируйте высоконагруженный поисковый сервис.',
    answer:
      'Разбить на: ingress/load balancer, сервисы запросов, индекс поиска (Elasticsearch), кэш (Redis), БД. Ключевые метрики: p95 latency, утилизация шардов. Обратить внимание на отказоустойчивость и деградацию.',
    difficulty: 'hard',
    rating: 4.8,
  },
  {
    id: 'iq-2',
    category: 'JavaScript',
    question: 'Чем отличается == от === и когда это важно?',
    answer:
      '== сравнивает со приведением типов, === без приведения. В продакшене использовать ===, чтобы избежать неявных багов.',
    difficulty: 'easy',
    rating: 4.2,
  },
  {
    id: 'iq-3',
    category: 'React',
    question: 'Что такое reconciliation и зачем React нужен key?',
    answer:
      'Reconciliation — процесс сравнения виртуального DOM. key позволяет React' + 'u эффективно переиспользовать узлы при ререндере списков.',
    difficulty: 'medium',
    rating: 4.6,
  },
  {
    id: 'iq-4',
    category: 'Архитектура',
    question: 'Монолит или микросервисы? Как выбираете?',
    answer:
      'Начинать с монолита, модульный монолит. Переходить на микросервисы при реальных потребностях масштабирования и команды.',
    difficulty: 'medium',
    rating: 4.5,
  },
  {
    id: 'iq-5',
    category: 'Тестирование',
    question: 'Как тестировать React-приложения на разных уровнях?',
    answer:
      'Unit (Jest + RTL) для логики и компонентов, интеграционные для взаимодействий, E2E (Playwright) для критических сценариев.',
    difficulty: 'medium',
    rating: 4.3,
  },
  {
    id: 'iq-6',
    category: 'Безопасность',
    question: 'Что такое CSRF и как защититься?',
    answer:
      'CSRF — атака, использующая авторизованную сессию пользователя. Защита: CSRF-токены, SameSite cookies, проверка Origin/Referer.',
    difficulty: 'hard',
    rating: 4.0,
  },
];

export const initialCareerGoals: CareerGoal[] = [
  {
    id: 'goal-1',
    title: 'Перейти на роль Tech Lead',
    timeframe: '6 месяцев',
    status: 'active',
    progress: 60,
    milestones: ['Провести 2 архитектурных ревью', 'Запустить менторскую программу', 'Опубликовать техническую статью'],
  },
  {
    id: 'goal-2',
    title: 'Выход на зарплату 9 000$+',
    timeframe: '12 месяцев',
    status: 'planned',
    progress: 15,
    milestones: ['Достичь Principal-уровня', '3 оффера на 9k+'],
  },
  {
    id: 'goal-3',
    title: 'Сертификация AWS Solutions Architect',
    timeframe: '3 месяца',
    status: 'completed',
    progress: 100,
    milestones: ['Пройден курс', 'Экзамен сдан'],
  },
];
